---
- name: Configure SonarQube
  hosts: localhost
  gather_facts: false
  vars:
    sonar_url: "http://{{ sonar_host }}:{{ sonar_port }}"
    default_user: admin
    default_password: admin
    token_name: "ci-token-{{ lookup('pipe', 'date +%s') }}"
  tasks:
    - name: Wait for SonarQube to be ready
      uri:
        url: "{{ sonar_url }}/api/system/status"
        method: GET
        user: "{{ default_user }}"
        password: "{{ default_password }}"
        force_basic_auth: yes
        status_code: 200
      register: sonar_status
      until: sonar_status is success and sonar_status.json.status == "UP"
      retries: 30
      delay: 12

    - name: Check if default password still works
      uri:
        url: "{{ sonar_url }}/api/authentication/validate"
        method: GET
        user: "{{ default_user }}"
        password: "{{ default_password }}"
        force_basic_auth: yes
        status_code: [200, 401]
      register: default_auth_check
      failed_when: false

    - name: Check if new password already works
      uri:
        url: "{{ sonar_url }}/api/authentication/validate"
        method: GET
        user: "{{ default_user }}"
        password: "{{ new_admin_password }}"
        force_basic_auth: yes
        status_code: [200, 401]
      register: new_auth_check
      failed_when: false

    - name: Change default admin password
      uri:
        url: "{{ sonar_url }}/api/users/change_password"
        method: POST
        user: "{{ default_user }}"
        password: "{{ default_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          login: "{{ default_user }}"
          previousPassword: "{{ default_password }}"
          password: "{{ new_admin_password }}"
        status_code: [200, 204]
      register: password_change
      when: default_auth_check.status == 200 and new_auth_check.status == 401
      failed_when: false

    - name: Determine which password to use
      set_fact:
        current_password: "{{ new_admin_password if new_auth_check.status == 200 else default_password }}"

    - name: Debug password selection
      debug:
        msg:
          - "Default auth status: {{ default_auth_check.status }}"
          - "New password auth status: {{ new_auth_check.status }}"
          - "Password change status: {{ password_change.status | default('skipped') }}"
          - "Using new password: {{ new_auth_check.status == 200 }}"

    - name: Verify current credentials work
      uri:
        url: "{{ sonar_url }}/api/authentication/validate"
        method: GET
        user: "{{ default_user }}"
        password: "{{ current_password }}"
        force_basic_auth: yes
        status_code: 200
      register: auth_verification

    - name: Wait for password change to propagate
      pause:
        seconds: 3
      when: password_change.changed | default(false)

    - name: Generate SonarQube token
      uri:
        url: "{{ sonar_url }}/api/user_tokens/generate"
        method: POST
        user: "{{ default_user }}"
        password: "{{ current_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          name: "{{ token_name }}"
        status_code: 200
      register: token_response
      no_log: false

    - name: Set token fact
      set_fact:
        sonar_token: "{{ token_response.json.token }}"
      no_log: true

    - name: Verify token works
      uri:
        url: "{{ sonar_url }}/api/authentication/validate"
        method: GET
        user: "{{ sonar_token }}"
        password: ""
        force_basic_auth: yes
        status_code: 200
      register: token_validation

    - name: Fail if token is invalid
      fail:
        msg: "Token validation failed"
      when: token_validation.json.valid != true

    - name: Save token to file (for GitHub Actions output)
      copy:
        content: "{{ sonar_token }}"
        dest: /tmp/sonar_token
        mode: "0600"
      no_log: false

    - name: Display success message
      debug:
        msg: "SonarQube configured successfully at {{ sonar_url }}"
