name: CI/CD pipeline-be

on:
  workflow_call:
    inputs:
      sonarqube_host:
        description: "the host URL"
        type: string
        required: true
    outputs:
      be_image_tag:
        description: just the backend tag
        value: ${{jobs.build_test_scan_push_be.outputs.be_image_tag}}

env:
  TF_WORKING_DIR: ./terraform-sonarqube

jobs:
  build_test_scan_push_be:
    runs-on: ubuntu-latest
    outputs:
      be_image_tag: ${{steps.output-step.outputs.be_image_tag}}
    steps:
      - name: checkout the repository
        uses: actions/checkout@v5

      - name: git commit
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "COMMIT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Install dependencies
        working-directory: ./backend
        run: mvn clean install -DskipTests

      - name: Run tests
        working-directory: ./backend
        run: mvn test

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{env.TF_WORKING_DIR}}
        run: terraform init

      - name: Retrieve Sonar Token
        run: |
          KeyVaultName=$(cd ${{env.TF_WORKING_DIR}} && terraform output -raw kv_name)
          SONAR_TOKEN=$(az keyvault secret show \
            --vault-name "$KeyVaultName" \
            --name "sonarqube-token" \
            --query "value" -o tsv)

          echo "::add-mask::$SONAR_TOKEN"
          echo "::add-mask::$KeyVaultName"
          echo "SONAR_TOKEN=$SONAR_TOKEN" >> $GITHUB_ENV

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_HOST_URL: ${{ inputs.sonarqube_host }}
        with:
          args: >
            -Dsonar.projectKey=backend-project
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.projectBaseDir=backend

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{vars.BACKEND_IMAGE_NAME}}:latest
            ${{ vars.DOCKERHUB_USERNAME }}/${{vars.BACKEND_IMAGE_NAME}}:${{env.COMMIT_VERSION}}
      - name: Output image tag
        id: output-step
        run: echo "be_image_tag=${{env.COMMIT_VERSION}}" >> $GITHUB_OUTPUT
