name: CI/CD Pipeline to build, test, scan (with SonarQube) and publish Docker images

on:
    workflow_dispatch:
    workflow_call:
        inputs:
            sonarqube_host:
                description: "the host URL"
                type: string
                required: true
            sonarqube_token:
                description: "SonarQube Token"
                type: string
                required: true
env:
    image_name: "${{inputs.tier}}-image-project"

jobs:
    build_test_scan_push:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repository
              uses: actions/checkout@v5

            - name: git commit
              run: |
                  VERSION=$(git rev-parse --short HEAD)
                  echo "COMMIT_VERSION=$VERSION" >> $GITHUB_ENV

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Install dependencies
              working-directory: ./${{inputs.tier}}
              run: mvn clean install -DskipTests

            - name: Run tests
              working-directory: ./${{inputs.tier}}
              run: mvn test

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v6.0.0
              env:
                  SONAR_TOKEN: ${{ inputs.sonarqube_token }}
                  SONAR_HOST_URL: ${{ inputs.sonarqube_host }}
              with:
                  args: >
                      -Dsonar.projectKey=${{inputs.tier}}-project
                      -Dsonar.sources=src/main/java
                      -Dsonar.tests=src/test/java
                      -Dsonar.java.binaries=target/classes
                      -Dsonar.projectBaseDir=${{inputs.tier}}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: ./${{inputs.tier}}
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{env.image_name}}:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{env.image_name}}:${{env.COMMIT_VERSION}}
