name: Infrastructure Provisioning

on:
  workflow_call:

jobs:
  terraform_provision:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-all

    env:
      TF_VAR_sql_admin_username: ${{ secrets.sql_admin_username }}
      TF_VAR_sql_admin_password: ${{ secrets.sql_admin_password }}
      TF_VAR_subscription_id: ${{secrets.subscription_id}}
      TF_VAR_admin_password: ${{secrets.admin_password}} # These are for the VMs
      TF_VAR_admin_username: ${{secrets.admin_username}} # These are for the VMs

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply using the plan from the previous step
        run: terraform apply -auto-approve
