name: Master CI/CD Pipeline

on:
    push:
        branches: [main]
        paths-ignore:
            - "terraform-sonarqube/**"
            - "**.md"
            - ".gitignore"

jobs:
    detect-changes:
        runs-on: ubuntu-latest
        outputs:
            frontend: ${{ steps.filter.outputs.frontend }}
            backend: ${{ steps.filter.outputs.backend }}
            terraform: ${{ steps.filter.outputs.terraform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Detect Changes
              uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      frontend:
                        - 'frontend/**'
                      backend:
                        - 'backend/**'
                      terraform:
                        - 'terraform/**'
                        - '!terraform-sonarqube/**'

    run-sonarqube:
        needs: detect-changes
        if: needs.detect-changes.outputs.frontend == 'true' || needs.detect-changes.outputs.backend == 'true'
        uses: ./.github/workflows/sonarqube.yml
        secrets: inherit

    build-frontend:
        needs: [detect-changes, run-sonarqube]
        if: needs.detect-changes.outputs.frontend == 'true'
        uses: ./.github/workflows/fe.yml
        secrets: inherit
        with:
            sonarqube_token: ${{ needs.run-sonarqube.outputs.sonar_token }}
            sonarqube_host: ${{ needs.run-sonarqube.outputs.url }}

    build-backend:
        needs: [detect-changes, run-sonarqube]
        if: needs.detect-changes.outputs.backend == 'true'
        uses: ./.github/workflows/be.yml
        secrets: inherit
        with:
            sonarqube_token: ${{ needs.run-sonarqube.outputs.sonar_token }}
            sonarqube_host: ${{ needs.run-sonarqube.outputs.url }}

    deploy-infrastructure:
        needs: [detect-changes, build-frontend, build-backend]
        if: |
            always() &&
            !cancelled() &&
            !contains(needs.*.result, 'failure') &&
            (needs.detect-changes.outputs.frontend == 'true' ||
             needs.detect-changes.outputs.backend == 'true' ||
             needs.detect-changes.outputs.terraform == 'true')
        uses: ./.github/workflows/infrastructure.yml
        secrets: inherit

    workflow-summary:
        needs:
            [
                detect-changes,
                run-sonarqube,
                build-frontend,
                build-backend,
                deploy-infrastructure,
            ]
        if: always()
        runs-on: ubuntu-latest
        steps:
            - name: Generate Workflow Summary
              run: |
                  echo "## CI/CD Pipeline Execution Summary" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "### Changes Detected" >> $GITHUB_STEP_SUMMARY
                  echo "- **Frontend**: ${{ needs.detect-changes.outputs.frontend == 'true' && ' Changed' || ' No changes' }}" >> $GITHUB_STEP_SUMMARY
                  echo "- **Backend**: ${{ needs.detect-changes.outputs.backend == 'true' && ' Changed' || ' No changes' }}" >> $GITHUB_STEP_SUMMARY
                  echo "- **Terraform**: ${{ needs.detect-changes.outputs.terraform == 'true' && ' Changed' || ' No changes' }}" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "### Workflow Execution Results" >> $GITHUB_STEP_SUMMARY
                  echo "| Workflow | Status |" >> $GITHUB_STEP_SUMMARY
                  echo "|----------|--------|" >> $GITHUB_STEP_SUMMARY
                  echo "| SonarQube | ${{ needs.run-sonarqube.result == 'success' && ' Success' || needs.run-sonarqube.result == 'skipped' && ' Skipped' || ' Failed' }} |" >> $GITHUB_STEP_SUMMARY
                  echo "| Frontend Build | ${{ needs.build-frontend.result == 'success' && ' Success' || needs.build-frontend.result == 'skipped' && ' Skipped' || ' Failed' }} |" >> $GITHUB_STEP_SUMMARY
                  echo "| Backend Build | ${{ needs.build-backend.result == 'success' && ' Success' || needs.build-backend.result == 'skipped' && ' Skipped' || ' Failed' }} |" >> $GITHUB_STEP_SUMMARY
                  echo "| Infrastructure Deployment | ${{ needs.deploy-infrastructure.result == 'success' && ' Success' || needs.deploy-infrastructure.result == 'skipped' && ' Skipped' || ' Failed' }} |" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY

                  if [[ "${{ needs.run-sonarqube.outputs.sonar_url }}" != "" ]]; then
                    echo "###  SonarQube Details" >> $GITHUB_STEP_SUMMARY
                    echo "- **URL**: ${{ needs.run-sonarqube.outputs.sonar_url }}" >> $GITHUB_STEP_SUMMARY
                    echo "- **VM IP**: ${{ needs.run-sonarqube.outputs.vm_ip }}" >> $GITHUB_STEP_SUMMARY
                  fi
